/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seng4430_softwarequalitytool;

public class App {
    public String getGreeting() {
        return "Hello SENG4430!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
